style: styles in InfoSection component
AlanPinhon/url-shortening-page-ts pull request #13
Opened 2023-11-08 22:03 UTC by AlanPinhon

Estilos en el componente `<InfoSection/>` 🖌

2023-11-08 22:58 UTC, gonzalo-novak requested changes
¡Bien! Sólo vi un detalle ;D

2023-11-08 22:58 UTC, gonzalo-novak commented on src/components/ShortenedLinkItem/ShortenedLinkItemStyles.css
> +  background-color: #fff;
Veo que este color se repite más de 2 veces (en este archivo y en otros). Tal vez será bueno crear una variable para ese color :D

2023-11-09 00:27 UTC, AlanPinhon commented on src/components/ShortenedLinkItem/ShortenedLinkItemStyles.css
> +  background-color: #fff;
Va que va. Entonces hago la corrección a una variable para el color. 🐱‍👤

2023-11-09 01:04 UTC, gonzalo-novak approved these changes
Vientos! 🎉

2023-11-09 03:03 UTC, merged