style: interface slides when showing and hiding menu
AlanPinhon/url-shortening-page-ts pull request #16
Opened 2023-11-27 22:18 UTC by AlanPinhon

Se realizó la corrección del deslizamiento de la página cuando se muestra y oculta el menú. ⏫⏬

2023-11-30 04:52 UTC, gonzalo-novak requested changes

2023-11-30 04:52 UTC, gonzalo-novak commented on src/components/Navbar/Navbar.tsx
> +        <div ref={menuRef} onClick={closeMenu} className={`menu-container ${isMenuVisible ? 'show' : ''}`}>
Si mal no estoy, veo que ya no usas la referencia `menuRef`. Sería bueno borrarlo. 

Adicionalmente, otra solución sería poner un div dentro del container en plan:

```tsx
<div className={`menu-container ${isMenuVisible ? 'show' : ''}`}>
          <div className="nav-container">
            <div className="left">  
              <ul>
                <li><a className='nav-link' href="#">Features</a></li>
                <li><a className='nav-link' href="#">Pricing</a></li>
                <li><a className='nav-link' href="#">Resources</a></li>
              </ul>
            </div>
           
            <div className="menu-background" onClick={closeMenu} />
</div>
```
La clase `menu-background` tendría los estilos que asignaste para que el recuadro ocupe toda la pantalla. Al darle click a ese elemento puedes cambiar el state del menú para cerrarlo. De esa manera evitas la propagación de eventos puesto que inicialmente el onClick se lo seteas a todo el contenedor y por ende al darle click a un item del menú, éste se cierra, ya que el nav-container es hijo del div al que le seteaste el onClick. Con el snippet que sugerí arriba, evitas ese tipo de comportamiento. Sin embargo, es sólo otra solución a tomar en cuenta.

Sólo quita el ref `menuRef` si no se utiliza 🐰

2023-11-30 04:52 UTC, gonzalo-novak commented on src/components/Navbar/Navbar.tsx
> +      <nav id="navbar" className="navbar">
Es redundante que una etiqueta nav tenga un id llamado `navbar`con una clase llamada `navbar` 🛩️

2023-11-30 04:52 UTC, gonzalo-novak commented on src/components/Navbar/Navbar.tsx
>          </div>
Veo que estas imagenes están dentro del nav tag. Normalmente un nav tag sólo tendrá los links de navegación. La semantica en HTML es un poco dificil de recordar; puedes apoyarte de ChatGPT para poder ver si tu HTML es semántico ;D

2023-11-30 04:55 UTC, gonzalo-novak commented on src/components/Navbar/NavbarStyles.css
>      transform: translateY(-150%);
No olvides añadir un `display: none` o `visibility: hidden` para que no se vea la animación del menu yéndose arriba en primer instancia. Por ende, no olvides de mostrarlo en la clase `.show`

2023-11-30 21:29 UTC, AlanPinhon commented on src/components/Navbar/Navbar.tsx
> +        <div ref={menuRef} onClick={closeMenu} className={`menu-container ${isMenuVisible ? 'show' : ''}`}>
Olvidé eliminar la referencia del menú. Esa corrección ya está hecha. 👻

2023-11-30 21:40 UTC, AlanPinhon commented on src/components/Navbar/Navbar.tsx
>          </div>
Me ayudé de ChatGTP para organizar la semántica en el HTML. Ya está actualizada esa parte. 🐤

2023-12-01 05:42 UTC, gonzalo-novak approved these changes
¡Bien!

2023-12-01 05:46 UTC, gonzalo-novak commented on src/components/Navbar/Navbar.tsx
>          </div>
¡Bien! Sólo como recordatorio: Trata de entender el código y de igual manera mantén tu nivel de criterio ya que a veces ChatGPT se inventa ciertas cosas. Sólo intenta tener ese balance entre verificar la info que te da ChatGPT con base a tus conocimientos y criterio propio y lo que ChatGPT te entrega 🎉

2023-12-01 17:30 UTC, AlanPinhon commented on src/components/Navbar/Navbar.tsx
>          </div>
De acuerdo. En las próximas prácticas tendré en cuenta eso. Incluso en la ayuda que me dio ChatGPT, solo tomé en cuenta algunas cosas y en otras tuve mi criterio. 🤘🏼

2023-12-01 17:31 UTC, merged