test: tests in LinkInput
AlanPinhon/url-shortening-page-ts pull request #8
Opened 2023-10-20 19:52 UTC by AlanPinhon

Pruebas en el componente `LinkInput` 🧪 :

-Renderiza el componente de manera inicial 🚩
-Muestra un mensaje cuando el input esté vacío 🏳
-Muestra un mensaje cuando el enlace ingresado es incorrecto ❌
-Llama la función `onAddShortLink` con el enlace válido ✔

2023-10-20 20:14 UTC, gonzalo-novak requested changes

2023-10-20 20:14 UTC, gonzalo-novak commented on tests/components/LinkInput.spec.tsx
> +  });
Después de ver este test, veo que las validaciones del input se hacen afuera del componente. Lo ideal sería que esas validaciones se hagan dentro del LinkInput, y si todo está OK, entonces se ejecutaría la función `onAddShortLink` 🌵

2023-10-20 22:38 UTC, AlanPinhon commented on tests/components/LinkInput.spec.tsx
> +  });
Ya hice los ajustes. Espero haber entendido bien los cambios. 🔄

2023-10-23 16:56 UTC, gonzalo-novak approved these changes
¡Vientos! 👏🏻 🎉

2023-10-23 19:11 UTC, merged