test: tests in ShortedLink component
AlanPinhon/url-shortening-page-ts pull request #9
Opened 2023-10-23 23:32 UTC by AlanPinhon

Pruebas en el componente ShortedLink: 🧪

-Debe comprobar que la solicitud POST se efectúe tanto de manera errónea❌  como de forma exitosa. ✔
_-Debatible_: Comprobar que se almacene y persista información en `localStorage` 📥

2023-10-24 01:42 UTC, gonzalo-novak approved these changes
¡Bien! 🎉 🌮

2023-10-24 16:42 UTC, gonzalo-novak commented on tests/components/ShortedLink/ShortedLink.spec.tsx
> +  });
Mas bien estos tests deberían usar el componente en donde haces la llamada a la API y registras el resultado en localStorage. Por ende, tendrías que simular un flujo donde le envías la URL y después de darle el submit, tendrías que revisar si ya está dicho link en la lista a nivel interfaz y luego revisar el localStorage para ver si se guardó dicho link 🦘

2023-10-25 01:16 UTC, AlanPinhon commented on tests/components/ShortedLink/ShortedLink.spec.tsx
> +  });
He hecho las actualizaciones y espero haber comprendido bien el flujo de las pruebas. Si no hazme saber que correcciones y mejoras debo hacer. 🤖

2023-10-25 17:44 UTC, gonzalo-novak requested changes
Veo que los tests utiliza la función `getShortedLink` de manera separada, al igual que el registro del resultado en localStorage. 

El test de este componente sería más de integración, en donde montas el componente `ShortedLink` y de ahí ya vas interactuando con todos sus elementos, en este caso el input y la lista de links acortados. 

Trata de montar ese componente y sólo sigue el flujo como si lo estuvieras haciendo a nivel interfaz. Lo que debes revisar es que una vez que le des submit, el link acortado debe aparecer en la lista inferior, y adicionalmente podrías revisar si al hacer un `localStorage.getItem('links')` es diferente a nulo. Si lo es, quiere decir que se registró el link a `localStorage` de manera exitosa 🎃

2023-10-29 19:23 UTC, gonzalo-novak reviewed
¡Vientos! Vas por buen camino 🎉 

Sólo hay algunos comentarios 👏🏻

2023-10-29 19:23 UTC, gonzalo-novak commented on tests/components/ShortedLink/ShortedLink.spec.tsx
> +import { userEvent } from '@testing-library/user-event';
A pesar de que comenzaste a utilizar esta librería (el cual está bien), veo que hay tests que aún usan la función `fireEvent`. Lo recomendable es que uses el `userEvent` si lo tienes instalado 🍰

2023-10-29 19:23 UTC, gonzalo-novak commented on tests/components/ShortedLink/ShortedLink.spec.tsx
> +      expect(error).toBeTruthy();
Me acabo de dar cuenta el por qué este test está así. Veo que a nivel código, si falla la petición, sólo muestras un `console.log`, el cual no es muy viable puesto que si sale algo mal, no le estás dando ese feedback al usuario a nivel interfaz. Sería bueno que ese error lo muestres en pantalla, ya sea debajo del input o utilizar toast component, por ejemplo el siguiente: https://react-hot-toast.com/ (yo no lo he usado, pero es un ejemplo). 🐥 

De esta manera le estamos mostrando los errores al usuario y podrá ser fácilmente encontrado con testing library:

```tsx
  test('should simulate a failed POST request', async () => {
    const errorDataResponse = {ok: false, message: 'Error processing link'};

    server.use(
      rest.post('https://api-ssl.bitly.com/v4/shorten', (_req,res,ctx) => {
        return res(
          ctx.status(500), ctx.json(errorDataResponse)
        )
      })
    );
    const validLink = 'https://www.youtube.com/';
    render(<ShortedLink/>);

    const linkInput = screen.getByPlaceholderText('Shorten a link here...') as HTMLInputElement;
    const shortenBtn = screen.getByText('Shorten it!');

    fireEvent.change(linkInput, {target: {value: validLink}})
    fireEvent.click(shortenBtn);

    expect(await screen.findByText("Error processing link")).toBeDefined()
  });
```

2023-10-29 19:23 UTC, gonzalo-novak commented on tests/components/ShortedLink/ShortedLink.spec.tsx
> +  });
Aquí aún no me queda claro este test case en donde la función de copy pudiera fallar. Con base a esas interacciones ¿cómo es que falla? 🤓

2023-10-29 19:23 UTC, gonzalo-novak commented on tests/components/ShortedLink/ShortedLink.spec.tsx
>    });
Es un poco extraño que puedas acceder a los links guardados desde otros test cases. Sólo ten cuidado con la persistencia de datos entre test cases, te pueden dar un mega dolor de cabeza en un futuro. Recomiendo que limpies el localStorage después o antes de iniciar un test case para que cada test esté lo más aislado posible 🦆 

Esto lo puedes poner después de que abres tu `describe`

```tsx
describe("Tests!", () => {
// Esto se ejecuta después de cada test
  afterEach(() => {
    localStorage.clear();
  })

 // Ya después siguen aquí todos los tests que vayas a escribir... ;D
})
```

2023-10-31 02:59 UTC, AlanPinhon commented
Ya están realizados los cambios en las pruebas. Si llega a salir algún otro comentario o cambio estoy atento. ☝🏼🤓

2023-10-31 22:56 UTC, gonzalo-novak commented on package.json
> +    "react-hot-toast": "^2.4.1"
Parece ser que se te olvidó eliminar la dependencia de aquí 🤖

2023-10-31 22:56 UTC, gonzalo-novak commented on tests/components/LinkInput/LinkInput.spec.tsx
> +    screen.debug();
Como ahora dependemos de un estado externo para mostrar el mensaje de error en la interfaz, tal vez deberías crear un test en el archivo `shortedlink.spec.tsx` donde, de igual manera, puedas interacturar con los elementos y hacer que esos errores se muestren en la interfaz para asegurarse que realmente aparece en el DOM. 👻

2023-10-31 22:56 UTC, gonzalo-novak commented on tests/components/LinkInput/LinkInput.spec.tsx
>    test('should show an error if the input value is empty', () => {
Como ahora nos enfocamos de que el `setErrorMsgMock` se mande a llamar con el mensaje de error, creo que la descripción de los tests debería cambiar como tal, ya que al menos en este contexto no estamos mostrando un mensaje de error 🐤

2023-11-01 04:25 UTC, AlanPinhon commented on package.json
> +    "react-hot-toast": "^2.4.1"
Olvidé eliminarla pero ahora ya lo está. 🤡

2023-11-01 04:26 UTC, AlanPinhon commented
Están realizados los últimos cambios. De todas formas cualquier otra cosa que surja le echo un ojo. 🐤

2023-11-02 00:49 UTC, gonzalo-novak approved these changes
Vientos!

2023-11-02 01:37 UTC, merged